config/routes.rb
Rails.application.routes.draw do
  resources :random_sets  do
    resources :lotteries, only: [ :new, :create, :index, :edit, :update, :destroy ]
  end
  resources :users, only: %i[new create show edit update destroy]
  get "/favorite/:id/:random_set_id", to: "favorite#flip_favorite", as: "flip_favorite"
  delete "/users/:id/:random_set_id", to: "users#destroy_list", as: "user_destroy_list"
  get "/random_sets/:id/new_list", to: "random_sets#new_list", as: "new_list"
  post "/random_sets/:id/create_list", to: "random_sets#create_list", as: "create_list"
  get "/random_sets/:id/edit_list", to: "random_sets#edit_list", as: "edit_list"
  post "/random_sets/:id/update_list", to: "random_sets#update_list", as: "update_list"
  delete "/random_sets/:id/destroy_list", to: "random_sets#destroy_list", as: "destroy_list"
  get "/login/:id", to: "session#new", as: "login"
  post "/login/:id", to: "session#create", as: "create_login"
  delete "/logout/:id", to: "session#destroy", as: "logout"
  get "/home", to: "static_pages#home"
  get "/guide", to: "static_pages#guide"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    reject_params_by_session_mode if params[:session_mode].nil?
    case params[:session_mode]
    when "random_set"
      @random_set = RandomSet.find(params[:id])
    when "user"
    end
  end

  def create
    reject_params_by_session_mode if params[:session][:session_mode].nil?
    case params[:session][:session_mode]
    when "random_set"
      @current_set = RandomSet.find(params[:id])
      if @current_set.id && @current_set&.authenticate(params[:session][:password])
        keep_reset_session("random_set")
        remember(@current_set, params[:session][:password])
        log_in @current_set
        render turbo_stream: turbo_stream.action(:redirect, edit_random_set_path(@current_set))
      else
        respond_to do |format|
          message = "パスワードが異なります"
          if params[:session][:password].blank?
            message = "パスワードを入力してください"
          end
          format.turbo_stream { flash.now.alert = message }
          format.html { render "new", status: :unprocessable_entity, session_mode: "random_set" }
        end
      end
    when "user"
      @current_user = User.find_by(user_id: params[:session][:user_id])
      if @current_user&.authenticate(params[:session][:password])
        keep_reset_session("user")
        user_remember(@current_user)
        user_log_in @current_user
        render turbo_stream: turbo_stream.action(:redirect, user_path(@current_user))
      else
        puts "test"
        respond_to do |format|
          message = "IDまたはパスワードが異なります"
          format.turbo_stream { flash.now.alert = message }
          format.html { render "new", status: :unprocessable_entity, session_mode: "user" }
        end
      end
    end
  end

  def destroy
    reject_params_by_session_mode if params[:session_mode].nil?
    case params[:session_mode]
    when "random_set"
      set_log_out if logged_in?
      render turbo_stream: turbo_stream.action(:redirect, random_sets_path)
    when "user"
      user_log_out if user_logged_in?
      render turbo_stream: turbo_stream.action(:redirect, root_path)
    end
  end

  def reject_params_by_session_mode
    respond_to do |format|
      message = "不適正な情報です。処理を再度やり直してください。"
      format.turbo_stream { flash.now.alert = message }
      format.html { render "new", status: :unprocessable_entity }
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
  # random_set
  def log_in(random_set)
    session[:set_session_token] = random_set.session_digest
  end

  # セッションの検証を行い、RandomSetに登録されているセッションと合致していればパススルー
  def current_set_session
    get_random_set()
    if (session_token = session[:set_session_token])
      if @random_set && session_token == @random_set.session_digest
        @current_set = @random_set
      end
    end
  end

  def remember(random_set, password)
    random_set.remember
    cookies.permanent[:set_id] = random_set.id
    cookies.permanent.encrypted[:password_token] = password
  end
  def get_random_set
    @random_set = RandomSet.find(params[:random_set_id]) if params[:random_set_id].present?
    @random_set = RandomSet.find(params[:id]) if @random_set.nil?
  end
  def get_session_password
    cookies.encrypted[:password_token]
  end
  def set_log_out
    cookies.permanent[:set_id] = nil
    set = RandomSet.find_by(session_digest: session[:set_session_token])
    set.forget
    session[:set_session_token] = nil
  end

  # user
  def user_log_in(user)
    session[:user_session_token] = user.session_digest
  end
  def current_user_session
    @user = User.find_by(id: cookies[:user_id])
    if session_token = session[:user_session_token]
      if @user && session[:user_session_token] == @user.session_digest
        @current_user = @user
      end
    end
  end
  def user_remember(user)
    user.remember
    cookies.permanent[:user_id] = user.id
  end
  def user_log_out
    cookies.permanent[:user_id] = nil
    user = User.find_by(session_digest: session[:user_session_token])
    user.forget
    session[:user_session_token] = nil
  end

  # ユーティリティー
  # reset_session処理、ユーザーログインはキープする。
  def keep_reset_session(delete_session_name)
    # sessionの深いコピーを行う
    cache = {}
    session.each { |i| cache.store(i[0], i[1]) }
    reset_session
    # delete対象以外をコピーしてtokenを残す
    session[:user_session_token] = cache["user_session_token"] if !delete_session_name.include?("user") && defined?(session[:user_session_token]).present?
    session[:set_session_token] = cache["set_session_token"] if !delete_session_name.include?("random_set") && defined?(session[:set_session_token]).present?
  end
  # 各種ログインチェック
  def logged_in?
    !current_set_session.nil?
  end
  def user_logged_in?
    !current_user_session.nil?
  end
  # セッションモードの判定
  def session_mode_check
    defined?(params[:session][:session_mode]).nil? ? params[:session_mode] : params[:session][:session_mode]
  end
end

app/views/session/_password_flash.html.erb
<%= turbo_frame_tag "password_flash" do %>
  <% if flash.alert.present? %>
    <div class="alert alert-danger">
      <%= flash.alert %>
    </div>    
  <% end %>
<% end %>

app/views/session/create.turbo_stream.erb
<%= turbo_stream.replace "session" %>
<%= turbo_stream.append "password_flash", partial: "password_flash" %>

app/views/session/new.html.erb
<%= turbo_frame_tag "session" do %>
  <%= render "modal", title: params[:title] do %>
    <%= form_with(url: login_path, scope: :session, html: { data: { action: "turbo:submit-end->previewModal#close" } }) do |f| %>
      <%= f.hidden_field :session_mode, value: session_mode_check() %>
      <%= render "password_flash" %>
      <% if session_mode_check() == "random_set" %>
        <div class="input-group">
          <%= f.password_field :password, class: "form-control", required: true %>

          <%= f.submit "検証", class: "btn btn-primary" %>
        </div>
      <% elsif session_mode_check() == "user" %>
        <div class="input-group mb-3">
          <%= f.label :user_id, t("common.user_id"), class: "input-group-text" %>
          <%= f.text_field :user_id, class: "form-control", required: true %>
        </div>
        <div class="input-group mb-3">
          <%= f.label :password, t("common.password"), class: "input-group-text" %>
          <%= f.password_field :password, class: "form-control", required: true %>
        </div>
        <p class="form-text">新規ユーザーは
          <%= link_to "こちら", new_user_path, data: { turbo_frame: "_top" } %>
          から作成<br>
          ※ユーザー作成せずにセットは作成できます。
        </p>
        <%= f.submit "ログイン", class: "btn btn-primary p-3" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>