config/routes.rb
Rails.application.routes.draw do
  resources :random_sets  do
    resources :lotteries, only: [ :new, :create, :index, :edit, :update, :destroy ]
  end
  resources :users, only: %i[new create show edit update destroy]
  get "/favorite/:id/:random_set_id", to: "favorite#flip_favorite", as: "flip_favorite"
  delete "/users/:id/:random_set_id", to: "users#destroy_list", as: "user_destroy_list"
  get "/random_sets/:id/new_list", to: "random_sets#new_list", as: "new_list"
  post "/random_sets/:id/create_list", to: "random_sets#create_list", as: "create_list"
  get "/random_sets/:id/edit_list", to: "random_sets#edit_list", as: "edit_list"
  post "/random_sets/:id/update_list", to: "random_sets#update_list", as: "update_list"
  delete "/random_sets/:id/destroy_list", to: "random_sets#destroy_list", as: "destroy_list"
  get "/login/:id", to: "session#new", as: "login"
  post "/login/:id", to: "session#create", as: "create_login"
  delete "/logout/:id", to: "session#destroy", as: "logout"
  get "/home", to: "static_pages#home"
  get "/guide", to: "static_pages#guide"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_created_random_sets
  has_many :user_favorite_random_sets, dependent: :destroy
  validates :user_id, presence: true, length: { minimum: 3, maximum: 255 }, uniqueness: true
  has_secure_password

  # アカウント関係
  def remember
    session = User.new_token
    update_attribute(:session_digest, User.digest(session))
    session_digest
  end

  def forget
    update_attribute(:session_digest, nil)
  end

  def session_check(session_password)
    return false if session_password.blank?
    BCrypt::Password.new(password_digest).is_password?(session_password)
  end

  # 中間テーブル関係
  def add_favorite(random_set)
    UserFavoriteRandomSet.create!(user_id: self.id, random_set_id: random_set.id)
  end
  def has_favorite?(random_set)
    UserFavoriteRandomSet.where(user_id: self.id, random_set_id: random_set.id).present?
  end
  def flip_favorite(random_set)
    if has_favorite?(random_set)
      delete_favorite(random_set)
      false
    else
      add_favorite(random_set)
      true
    end
  end
  def delete_favorite(random_set)
    target = UserFavoriteRandomSet.where("user_id = #{self.id} and random_set_id = #{random_set.id}").first
    return false if target.nil?
    target.destroy!
  end
  # user.favorite_all.eachで各random_set情報取得
  def favorite_all
    User.preload(user_favorite_random_sets: :random_set).find(self.id).user_favorite_random_sets
  end

  def add_create_random_set(random_set_params)
    self.transaction do
      random_set = RandomSet.create!(random_set_params)
      add_random_set(random_set)
    end
  end
  def add_random_set(random_set)
    UserCreatedRandomSet.create!(user_id: self.id, random_set_id: random_set.id)
  end
  def delete_create(random_set)
    target = UserCreatedRandomSet.where("user_id = #{self.id} and random_set_id = #{random_set.id}").first
    return false if target.nil?
    target.destroy
  end
  def created_all
    User.preload(user_created_random_sets: :random_set).find(self.id).user_created_random_sets
  end

  class << self
    # ログイン関係
    def new_token
      SecureRandom.urlsafe_base64
    end
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user_loggin?, only: %i[show edit update destroy destroy_list]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        reset_session
        user_remember(@user)
        user_log_in(@user)
        format.turbo_stream { flash.now.notice = @user.user_id + "を作成しました。" }
        render turbo_stream: turbo_stream.action(:redirect, user_path(@user))
      else
        format.turbo_stream { flash.now.alert = "作成に失敗しました。" }
        format.html { render "new", status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    @favorities = @user.favorite_all
    @created = @user.created_all
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find_by(id: params[:id])
    user_log_out
    @user.destroy! unless @user.nil?
    render turbo_stream: turbo_stream.action(:redirect, root_path)
  end

  def destroy_list
    user = User.find(params[:id])
    @target_set = RandomSet.find_by(id: params[:random_set_id])
    case params[:list_mode]
    when "favorite"
      user.delete_favorite(@target_set)
      respond_to do |format|
        @destroy_list_target = "favorite"
        format.turbo_stream { flash.now.notice = @target_set.name.to_s + "をお気に入りから削除しました。" }
        format.html { render "destroy_favorite", deleted_id: @target_set.id }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:user_id, :password)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_created.html.erb
<%= turbo_frame_tag "created" do %>
  <div class="card">
    <div class="card-header">
      作成したセット
    </div>
    <div class="card-body">
      <% if @created.empty? %>
        <p>
          まだセットを作成したことがありません。<br>
          作成してみませんか？<br><br>
          <%= link_to "セット作成へ", new_random_set_path, data: { turbo_frame: "_top" } %>
        </p>
      <% else %>
        <ul class="list-group list-group-flush">
          <% @created.each do |create| %>
            <li class="list-group-item">
              <div class="row">
                <div class="col">
                  <%= link_to random_set_path(create.random_set.id), data: { turbo_frame: "_top" } do %>
                    <span class="bi bi-box-arrow-up-left"><%= create.random_set.name %></span>
                  <% end  %>
                  <span class="bi bi-heart-fill icon-pink"></span><%= create.random_set.favorities_count %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_favorite.html.erb
<%= turbo_frame_tag "favorite" do %>
  <div class="card">
    <div class="card-header">
      登録したお気に入り
    </div>
    <div class="card-body">
      <% if @favorities.empty? %>
        <p>
          まだお気に入りが登録されていません。<br>
          登録してみませんか？<br><br>
          <%= link_to "セット検索へ", random_sets_path, data: { turbo_frame: "_top" } %>
        </p>
      <% else %>
        <ul class="list-group list-group-flush">
        <% @favorities.each do |favorite| %>
          <li class="list-group-item">
            <%= render "favorite_list", favorite: favorite.random_set %>
          </li>
        <% end %>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_favorite_list.html.erb
<%= turbo_frame_tag "random_set_favorite_#{favorite.id}" do %>
  <div class="row">
      <div class="d-flex">
        <div class="col">
          <%= link_to random_set_path(favorite.id), data: { turbo_frame: "_top" } do %>
            <span class="bi bi-box-arrow-up-left"><%= favorite.name %></span>
          <% end %>
          <span class="bi bi-heart-fill icon-pink"></span><%= favorite.favorities_count %>
        </div>
        <div class="d-flex justify-content-end">
          <%= button_to "削除", user_destroy_list_path(id: @user.id, random_set_id: favorite.id, list_mode: "favorite"),
            id: "favorite_delete_button_#{favorite.id}",
            method: :delete,
            class: "btn btn-danger btn-small",
            form: { data: { turbo_confirm: "#{favorite.name}をお気に入りから削除してもよろしいですか？" } }
          %>
        </div>
    </div>
  </div>
<% end %>

app/views/users/_new_form.html.erb
<%= turbo_frame_tag "user_form" do %>
  <%= form_with(model: @user) do |form| %>
    <%= render "form_flash", object: form.object %>
    <div class="input-group mb-3">
      <%= form.label :user_id, class: "input-group-text", id: "random_set_name" %>
      <%= form.text_field :user_id, class: "form-control", placeholder: "3文字～255文字まで", aria: { describedby: "random_set_name" }, required: true %>
    </div>

    <div class="input-group mb-3">
      <%= form.label :password, class: "input-group-text", id: "random_set_password" %>
      <%= form.password_field :password, class: "form-control", placeholder: "パスワード", aria: { describedby: "random_set_password" }, required: true  %>
    </div>

    <div>
      <%= form.submit "作成", class: "btn btn-primary p-3" %>
    </div>
  <% end %>
<% end %>

app/views/users/_user_info.html.erb
<div class="card mb-3">
  <div class="card-header">
    <div class="row">
      <span class="col bi bi-person-fill">ユーザー情報</span>
    </div>
  </div>
  <div class="card-body">
    <div class="row mb-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <span class="bi bi-person-fill"><%= t("common.user_id") %>：<%= @user.user_id %>
        </li>
        <li class="list-group-item">
          <span class="bi bi-hammer"></span>作成数：<%= @created.size %>
        </li>
        <li class="list-group-item">
          <span class="bi bi-heart-fill"></span>お気に入り数：<%= @favorities.size %>
        </li>
    </div>
    <div class="row d-flex">
      <div class="col-mb-1 d-flex flex-grow-0">
        <%= button_to "ログアウト", logout_path(id: @user.id, session_mode: "user"),
          method: :delete,
          class: "btn btn-warning p-3 mx-3",
          form: { data: { turbo_confirm: "ログアウトしますか？" } }
        %>
        <%= button_to "ユーザーの削除", user_path(@user),
          method: :delete,
          id: "user_delete_#{@user.id}",
          class: "btn btn-danger p-3 mx-3",
          form: { data: { turbo_confirm: "本当に削除しますか？（この削除では作成したセットは削除されません！）" } }
        %>
      </div>
    </div>
  </div>
</div>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.replace "user_form", partial: "new_form" %>
<%= turbo_stream.append "flashes", partial: "flash" %>

app/views/users/destroy_list.turbo_stream.erb
<%= turbo_stream.remove "random_set_favorite_#{@target_set.id}" if @destroy_list_target == "favorite" %>
<%= turbo_stream.append "flashes", partial: "flash" %>

app/views/users/new.html.erb
<% content_for :title, "ユーザー登録" %>
<%= turbo_frame_tag "user", class: "p-0" do %>

  <div class="p-0 m-0 max-height">
    <div class="row gx-0 align-items-center w-100 h-100 trump-img background-fix opacity-50"></div>
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="card w-50">
        <div class="card-header">
          <span class="bi bi-person-fill-add">ユーザー登録</span>
        </div>
        <div class="card-body">
          <%= render "new_form" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%= turbo_frame_tag "user" do %>
  <div class="mx-1 px-4 py-4 mt-5">
    <%= render "user_info" %>
    <div class="row">
      <div class="col-md-6">
        <%= render "favorite" %>
      </div>
      <div class="col-md-6">
        <%= render "created" %>
      </div>
    </div>
  </div>
<% end %>