config/routes.rb
Rails.application.routes.draw do
  resources :random_sets  do
    resources :lotteries, only: [ :new, :create, :index, :edit, :update, :destroy ]
  end
  resources :users, only: %i[new create show edit update destroy]
  get "/favorite/:id/:random_set_id", to: "favorite#flip_favorite", as: "flip_favorite"
  delete "/users/:id/:random_set_id", to: "users#destroy_list", as: "user_destroy_list"
  get "/random_sets/:id/new_list", to: "random_sets#new_list", as: "new_list"
  post "/random_sets/:id/create_list", to: "random_sets#create_list", as: "create_list"
  get "/random_sets/:id/edit_list", to: "random_sets#edit_list", as: "edit_list"
  post "/random_sets/:id/update_list", to: "random_sets#update_list", as: "update_list"
  delete "/random_sets/:id/destroy_list", to: "random_sets#destroy_list", as: "destroy_list"
  get "/login/:id", to: "session#new", as: "login"
  post "/login/:id", to: "session#create", as: "create_login"
  delete "/logout/:id", to: "session#destroy", as: "logout"
  get "/home", to: "static_pages#home"
  get "/guide", to: "static_pages#guide"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/random_set.rb
class RandomSet < ApplicationRecord
  has_many :lotteries, dependent: :destroy
  belongs_to :user_created_random_sets, optional: true
  has_many :user_favorite_random_sets
  validates :name, presence: :true, length: { minimum: 3, maximum: 255 }
  validates :pick_type, inclusion: { in: %w[mix box], message: "%{value} is not a valid status" }
  validates :pickup_type, inclusion: { in: %w[pre percent-ave percent-fix], message: "%[value] is not a valid status" }
  validates :default_value, comparison: { greater_than_or_equal_to: -1 }
  validate :rate_pickup_rate_with_array_into_fixed_hash
  before_save :list_sort_by_reality
  before_save :default_value_had_over_then_or_equal_values_list_sum


  has_secure_password

  # 検索設定
  def
    self.ransackable_attributes(auth_object = nil) [ "name", "id", "created_at", "updated_at" ]
  end

  # セッション情報の記録
  def remember
    session = RandomSet.new_token
    update_attribute(:session_digest, RandomSet.digest(session))
    session_digest
  end

  # セッション情報の破棄
  def forget
    update_attribute(:session_digest, nil)
  end

  # セッション情報の照合
  def session_check(session_password)
    return false if session_password.blank?
    BCrypt::Password.new(password_digest).is_password?(session_password)
  end

  # 制作者情報の取得
  def created_by
    users = UserCreatedRandomSet.preload(:user, :random_set).where(random_set_id: self.id)[0]
    if defined?(users.user).present?
      users.user
    end
  end

  class << self
      # 新たなトークンを与える
      def new_token
        SecureRandom.urlsafe_base64
      end

      # ハッシュを与える。
      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end
  end
  private
    def rate_pickup_rate_with_array_into_fixed_hash
      # rate,pickup_rateはArrayであること。
      unless rate.is_a?(Array) || pickup_rate.is_a?(Array) || value_list.is_a?(Array)
        return
      end

      rate.each_with_index do |item, index|
        check_into_fixed_hash(:rate, item, index)
      end

      pickup_rate.each_with_index do |item, index|
        check_into_fixed_hash(:pickup_rate, item, index)
      end

      value_list.each_with_index do |item, index|
        check_into_fixed_hash(:value_list, item, index)
      end
    end
    # 判定
    def check_into_fixed_hash(symbol, item, index)
      # そもそも何も入っていなければなし
      if item == []
        return
      end
      unless item.is_a?(Hash) && item.key?("reality") && item.key?("value")
        errors.add(symbol, "Itme index #{index} is invalid: Must include keys reality and value")
        return
      end

      unless item["reality"].is_a?(Numeric) && item["value"].is_a?(Numeric)
        errors.add(symbol, "Item index #{index} is invalid: Only values")
      end
    end
    # 配列の並びをレアリティ基準でソートする。
    def list_sort_by_reality
      unless rate.blank?
        self.rate = rate.sort_by { |target_data| target_data["reality"] }
      end
      unless pickup_rate.blank?
        self.pickup_rate = pickup_rate.sort_by { |target_data| target_data["reality"] }
      end
      unless value_list.blank?
        self.value_list = value_list.sort_by { |target_data| target_data["reality"] }
      end
    end
    # default_valueがvalue_listの合計より多いか
    def default_value_had_over_then_or_equal_values_list_sum
      if default_value == -1
        return
      end
      sum = self.value_list.map { |i| i["value"] }
      if sum.sum > self.default_value
        errors.add(:default_value, "default_value had over than value_lists sumed")
      end
    end
end

app/controllers/random_sets_controller.rb
class RandomSetsController < ApplicationController
  before_action :check_loggin?, only: [ :edit, :update, :destroy, :create_list, :update_list, :destroy_list ]

  # GET /random_sets or /random_sets.json
  def index
    @random_sets = RandomSet.all

    @search = RandomSet.ransack(params[:q])
    @search.sorts = "id desc" if @search.sorts.empty?
    @random_sets = @search.result
  end

  # GET /random_sets/1 or /random_sets/1.json
  def show
    @random_set = RandomSet.find(params[:id])
    # ModおよびValiant用
    if @random_set.parent.present?
      @parent_set = RandomSet.find(@random_set.parent)
    end
    @lotteries = @random_set.lotteries.select(:id, :name, :dict, :reality, :default_check, :default_pickup, :value)
  end

  # GET /random_sets/new
  def new
    @random_set = RandomSet.new
  end

  # GET /random_sets/1/edit
  def edit
    @random_set = RandomSet.find(params[:id])
    @lotteries = @random_set.lotteries.select(:id, :name, :dict, :reality, :default_check, :default_pickup, :value)
    @search = @lotteries.ransack(params[:q])
    @search.sorts = "id asc" if @search.sorts.empty?
    @lotteries = @search.result
  end

  def edit_elements
    @random_set = RandomSet.find(params[:id])
  end

  # POST /random_sets or /random_sets.json
  def create
    @random_set = RandomSet.new(random_set_params)
    if @random_set.save
      add_created_user_id() if user_logged_in?
      keep_reset_session("random_set")
      remember(@random_set, params[:random_set][:password])
      log_in(@random_set)
      render turbo_stream: turbo_stream.action(:redirect, edit_random_set_path(@random_set))
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /random_sets/1 or /random_sets/1.json
  def update
    @random_set = RandomSet.find(params[:id])
    respond_to do |format|
      if @random_set.update(random_set_params)
        format.turbo_stream { flash.now.notice = @random_set.name.to_s + "を更新しました。" }
        format.html { render "update" }
      else
        format.turbo_stream { flash.now.alert = "更新に失敗しました。" }
        format.html { render "edit", status: :unprocessable_entity }
      end
    end
  end


  # レアリティ抽選などのリスト用処理
  def new_list
    @action_path = create_list_path
    @random_set = RandomSet.find(params[:id])
    case params[:target_list]
    when "reality_list"
      @have_list =  @random_set.rate.map { |item| item["reality"] }
    when "pickup_list"
      @have_list =  @random_set.pickup_rate.map { |item| item["reality"] }
    when "value_list"
      @have_list = @random_set.value_list.map { |item| item["reality"] }
    end
  end

  def create_list
    @random_set = RandomSet.find(params[:id])
    @target_list = params[:random_set][:target_list]
    case params[:random_set][:target_list]
    when "reality_list"
      @random_set.rate.push({ "reality" => params[:random_set][:reality].to_i, "value" => params[:random_set][:value].to_i })
    when "pickup_list"
      @random_set.pickup_rate.push({ "reality" => params[:random_set][:reality].to_i, "value" => params[:random_set][:value].to_i })
    when "value_list"
      @random_set.value_list.push({ "reality" => params[:random_set][:reality].to_i, "value" => params[:random_set][:value].to_i })
    end

    respond_to do |format|
      if @random_set.save
        format.turbo_stream { flash.now.notice = @random_set.name.to_s + "に追加されました。" }
        format.html { render "create_list" }
      else
        format.turbo_stream { flash.now.alert = "追加に失敗しました。" }
        format.html { render "new_list", status: :unprocessable_entity }
      end
    end
end

  def edit_list
    @random_set = RandomSet.find(params[:id])
    @action_path = update_list_path
  end

  def update_list
    @random_set = RandomSet.find(params[:id])
    @target_list = params[:random_set][:target_list]
    begin
      case params[:random_set][:target_list]
      when "reality_list"
        target_data = @random_set.rate.filter { |item| item["reality"] == params[:random_set][:reality].to_i }
        target_data[0]["value"] = params[:random_set][:value].to_i
      when "pickup_list"
        target_data = @random_set.pickup_rate.filter { |item| item["reality"] == params[:random_set][:reality].to_i }
        target_data[0]["value"] = params[:random_set][:value].to_i
      when "value_list"
        target_data = @random_set.value_list.filter { |item| item["reality"] == params[:random_set][:reality].to_i }
        target_data[0]["value"] = params[:random_set][:value].to_i
      end
    rescue
      respond_to do |format|
        format.turbo_stream { flash.now.alert = "不正な値が書き込まれたため、失敗しました。" }
        format.html { render "edit_list", status: :unprocessable_entity }
        return 0
      end
    end

    respond_to do |format|
      if @random_set.save
        format.turbo_stream { flash.now.notice = @random_set.name.to_s + "に追加されました。" }
        format.html { render "update_list" }
      else
        format.turbo_stream { flash.now.alert = "更新に失敗しました。" }
        format.html { render "edit_list", status: :unprocessable_entity }
      end
    end
  end

  def destroy_list
    @random_set = RandomSet.find(params[:id])
    @target_list = params[:target_list]
    begin
      case params[:target_list]
      when "reality_list"
        target_index = @random_set.rate.find_index { |item| item["reality"] == params[:reality].to_i }
        @random_set.rate.delete_at(target_index)
      when "pickup_list"
        target_index = @random_set.pickup_rate.find_index { |item| item["reality"] == params[:reality].to_i }
        @random_set.pickup_rate.delete_at(target_index)
      when "value_list"
        target_index = @random_set.value_list.find_index { |item| item["reality"] == params[:reality].to_i }
        @random_set.value_list.delete_at(target_index)
      end
    rescue
      respond_to do |format|
        format.turbo_stream { flash.now.alert = "不正な値が書き込まれたため、失敗しました。" }
        format.html { render "destroy_list", status: :unprocessable_entity }
        return 0
      end
    end
    puts target_index

    respond_to do |format|
      if @random_set.save
        format.turbo_stream { flash.now.notice = @random_set.name.to_s + "から削除されました。" }
        format.html { render "destroy_list" }
      else
        format.turbo_stream { flash.now.alert = "削除に失敗しました。" }
        format.html { render "destroy_list", status: :unprocessable_entity }
      end
    end
  end

  # DELETE /random_sets/1 or /random_sets/1.json
  def destroy
    respond_to do |format|
      if @random_set.destroy!
        format.turbo_stream { flash.notice = "削除しました。" }
        render turbo_stream: turbo_stream.action(:redirect, random_sets_path)
      else
        format.turbo_stream { flash.now.alert = "削除に失敗しました。" }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_random_set
      @random_set = RandomSet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def random_set_params
      params.require(:random_set).permit(:name, :dict, :password, :pick_type, :rate, :pickup_rate, :value, :default_value)
    end

    # ユーザーログイン中に制作したら追加
    def add_created_user_id
      @current_user.add_random_set(@random_set)
    end
end

app/helpers/random_sets_helper.rb
module RandomSetsHelper
  # data要素の表示用
  def get_infomation_conversion(string)
    case string
    # type
    when "mix"
      "通常-独立"
    when "mix-tip"
      "個数の影響を無視します。個数の影響を受けません。"
    when "box"
      "ボックスガチャ-当選排除"
    when "box-tip"
      "ボックス容量が設定されており、抽選されるレアリティ・対象が固定されています。"

    when "pre"
      "事前選出"
    when "pre-tip"
      "当該レアリティが抽選された後、ピックアップ対象かそれ以外かの抽選を先に行います。"
    when "percent-ave"
      "単純当選率上昇-等分"
    when "percent-ave-tip"
      "当該レアリティが抽選された後、均等の抽選率に対してピックアップ対象の抽選率を決定します。ピックアップ対象が複数の場合、確率が等分されて反映されます。"
    when "percent-fix"
      "単純当選率上昇-固定"
    end
  end
  def chk_parameter(set)
    if set.pick_type.present? \
        && set&.rate != [] \
        && set&.pickup_rate != []
      true
    else
      false
    end
  end
  def get_list_parameter(random_set)
    case random_set
    when "reality_list"
      {
        "list" => "reality",
        "list_icon" => "bi-eyedropper",
        "list_name" => "レアリティ抽選率*",
        "quantity" => "%",
        "tooltip_message" => "設定されていないレアリティは余ってる確率を等分します。",
        "target_list" => @random_set.rate,
        "turbo_name" => "pickList",
        "min_value" => false,
        "new_path" => new_list_path(id: @random_set, target_list: "reality_list"),
        "create_path" => create_list_path(id: @random_set, target_list: "reality_list"),
        "edit_path" => edit_list_path(id: @random_set, target_list: "reality_list"),
        "update_path" => update_list_path(id: @random_set, target_list: "reality_list"),
        "destroy_path" => destroy_list_path(id: @random_set, target_list: "reality_list")
      }
    when "pickup_list"
      {
        "list" => "pickup",
        "list_icon" => "bi-star-fill",
        "list_name" => "ピックアップ確率*",
        "quantity" => "%",
        "tooltip_message" => "ピックアップ判定において利用されます。挙動については「ピックアップ抽選方式」を確認してください。",
        "target_list" => @random_set.pickup_rate,
        "turbo_name" => "pickupList",
        "min_value" => false,
        "new_path" => new_list_path(id: @random_set, target_list: "pickup_list"),
        "create_path" => create_list_path(id: @random_set, target_list: "pickup_list"),
        "edit_path" => edit_list_path(id: @random_set, target_list: "pickup_list"),
        "update_path" => update_list_path(id: @random_set, target_list: "pickup_list"),
        "destroy_path" => destroy_list_path(id: @random_set, target_list: "pickup_list")
      }
    when "value_list"
      {
        "list" => "value",
        "list_icon" => "bi-briefcase-fill",
        "list_name" => "レアリティ別個数",
        "quantity" => "個",
        "tooltip_message" => "レアリティ毎の抽選個数の制限です。",
        "target_list" => @random_set.value_list,
        "turbo_name" => "valueList",
        "min_value" => true,
        "new_path" => new_list_path(id: @random_set, target_list: "value_list"),
        "create_path" => create_list_path(id: @random_set, target_list: "value_list"),
        "edit_path" => edit_list_path(id: @random_set, target_list: "value_list"),
        "update_path" => update_list_path(id: @random_set, target_list: "value_list"),
        "destroy_path" => destroy_list_path(id: @random_set, target_list: "value_list")
      }
    end
  end
  def list_edit_action
    [ "edit", "update", "create_list", "update_list", "destroy_list" ]
  end
end

app/views/random_sets/_box_card.html.erb
<div class="card">
  <div class="card-header">
    <div class="row">
      <div class="col d-flex align-items-center">
        <div class="bi-box-fill" data-controller="tooltip" data-tooltip="このセット全体の個数です。0の時に引くとリセットがかかります。">ボックス全体数</div>
        <% if !list_edit_action.include?(params[:action]) %>
          <div class="col d-flex justify-content-end">
            <button class="btn btn-info btn-small" data-action="info#fixBox">固定</button>
            <button class="btn btn-warning btn-small" data-action="info#resetBox">リセット</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="form-text">※-1は無限として扱います。</div>
    <% if list_edit_action.include?(params[:action]) %>
      <%= form_with model: @random_set do |f| %>
        <div class="input-group">
          <%= f.number_field :default_value, class:"form-control" %>
          <%= f.submit "変更", class: "btn btn-primary py-3 px-4"%>
        </div>
      <% end %>
    <% else %>
      <div class="input-group mb-3">
        <input id="boxValue" type="number" class="form-control" value=<%= @random_set.default_value %> data-default-value=<%= @random_set.default_value %> min=-1 data-info-target="setValue" data-randomizer-target="setValue">
        <div class="input-group-text">個</div>
      </div>
      <div class="input-group mb-3">
        <div class="input-group-text"><small>ボックスリセット回数</small></div>
        <input type="number" class="form-control" value=0 data-default-value=0 data-info-target="setValue" data-randomizer-target="resetCount" disabled>
        <div class="input-group-text">回</div>
      </div>
      <div>ボックスリセット時の処理</div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="form-text">レアリティ別個数</div>
          <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" name="valueFrameResetPattern" value="reset" data-randomizer-target="valueFrameResetPattern" checked>
            <label class="form-check-label"><small>リセット</small></label>
          </div>
        </li>
        <li class="list-group-item">
          <div class="form-text">セットの個数</div>
          <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" name="lotteryValueResetPattern" value="reset" data-randomizer-target="lotteryValueResetPattern" checked>
            <label class="form-check-label"><small>リセット</small></label>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/random_sets/_form.html.erb
<%= form_with(model: random_set) do |form| %>
  <%= render "form_flash", object: form.object %>
  <div class="input-group mb-3">
    <%= form.label :name, class: "input-group-text", id: "random_set_name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "3文字～255文字まで", aria: { describedby: "random_set_name" }, required: true %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :dict, class: "input-group-text", id: "random_set_dict" %>
    <%= form.text_area :dict, class: "form-control", placeholder: "説明を入力", aria: { describedby: "random_set_dict" }  %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :password, class: "input-group-text", id: "random_set_password" %>
    <%= form.password_field :password, class: "form-control", placeholder: "編集時に使用するパスワード", aria: { describedby: "random_set_password" }, required: true  %>
  </div>

  <div>
    <%= form.submit "作成", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/random_sets/_infomation.html.erb
<%= turbo_frame_tag "random_set_infomation" do %>
  <div class="card" data-controller="info">
    <div class="card-header">
      <i class="bi bi-bar-chart">セット設定</i>
    </div>
    <div class="card-body">
      <% if chk_parameter(@random_set) || list_edit_action.include?(params[:action]) %>
        <div data-randomizer-target="infomation" data-setcheck="true">
          <div class="row">
            <div class="col-lg mb-3">
              <%= render "list", list_object: get_list_parameter("reality_list") %>
            </div>
            <div class="col-lg mb-3">
              <%= render "list", list_object: get_list_parameter("pickup_list") %>
            </div>
          </div>
          <% if @random_set.pick_type == "box" || list_edit_action.include?(params[:action]) %>
            <div class="row">
              <div class="col mb-3">
                <%= render "list", list_object: get_list_parameter("value_list") %>
              </div>
              <div class="col">
                <%= render "box_card" %>
              </div>
            </div>
          <% end %>
          <% if list_edit_action.include?(params[:action]) %>
            <div class="form-text">*必須要素</div>
          <% end %>
        </div>
      <% else %>
        <span data-randomizer-target="infomation" data-setcheck="false">設定がありません。編集にて設定を追加してください。</span>
      <% end %>
    </div>

    <%# モーダル要素 %>
    <div class="modal fade" data-info-target="infoModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">追加</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="input-group">
              <select class="form-select" style="width: -10%;" data-info-target="selectReality">
                <% get_realityname_list().each do |i| %>
                  <option value=<%= i %> data-info-target="realityTranslation" data-randomizer-target="realityTranslation"><%= get_realityname(i) %></option>
                <% end %>
              </select>
              <input id="addReality" class="form-control" type="number" step="0.1" min=-1 value=0 data-info-target="value">
            </div>
            <small>注：一時的な追加です。ページ移動をすると消去されます。</small>
          </div>
          <div class="modal-footer">
            <button class="btn btn-primary" data-action="click->info#add">追加</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/random_sets/_information.html.erb
<%= turbo_frame_tag "random_set_information" do %>
  <div class="card" data-controller="info">
    <div class="card-header">
      <i class="bi bi-bar-chart">セット設定</i>
    </div>
    <div class="card-body">
      <% if chk_parameter(@random_set) || list_edit_action.include?(params[:action]) %>
        <div data-randomizer-target="infomation" data-setcheck="true">
          <div class="row">
            <div class="col-lg mb-3">
              <%= render "list", list_object: get_list_parameter("reality_list") %>
            </div>
            <div class="col-lg mb-3">
              <%= render "list", list_object: get_list_parameter("pickup_list") %>
            </div>
          </div>
          <% if @random_set.pick_type == "box" || list_edit_action.include?(params[:action]) %>
            <div class="row">
              <div class="col mb-3">
                <%= render "list", list_object: get_list_parameter("value_list") %>
              </div>
              <div class="col">
                <%= render "box_card" %>
              </div>
            </div>
          <% end %>
          <% if list_edit_action.include?(params[:action]) %>
            <div class="form-text">*必須要素</div>
          <% end %>
        </div>
      <% else %>
        <span data-randomizer-target="infomation" data-setcheck="false">設定がありません。編集にて設定を追加してください。</span>
      <% end %>
    </div>

    <%# モーダル要素 %>
    <div class="modal fade" data-info-target="infoModal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">追加</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="input-group">
              <select class="form-select" style="width: -10%;" data-info-target="selectReality">
                <% get_realityname_list().each do |i| %>
                  <option value=<%= i %> data-info-target="realityTranslation" data-randomizer-target="realityTranslation"><%= get_realityname(i) %></option>
                <% end %>
              </select>
              <input id="addReality" class="form-control" type="number" step="0.1" min=-1 value=0 data-info-target="value">
            </div>
            <small>注：一時的な追加です。ページ移動をすると消去されます。</small>
          </div>
          <div class="modal-footer">
            <button class="btn btn-primary" data-action="click->info#add">追加</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/random_sets/_random_set.html.erb
<%= turbo_frame_tag random_set do %>
  <div class="row py-2 border-top">
    <div class="col-4 my-auto text-truncate">
      <%= random_set.name %>
    </div>
    <div class="col-4 my-auto text-truncate">
      <%= random_set.dict %>
    </div>
    <div class="col-4">
      <div class="d-flex justify-content-end">
        <%= link_to "確認", random_set_lotteries_path(random_set.id), class: "btn btn-sm btn-primary me-2", data: { turbo_frame: "preview_modal" } %>
        <%= link_to "選択", random_set_path(random_set), class: "btn btn-sm btn-secondary", data: { turbo_frame: "_top" } %>
      </div>
    </div>
  </div>
<% end %>

app/views/random_sets/create_list.turbo_stream.erb
<%= turbo_stream.append "flashes", partial: "flash" %>
<%= turbo_stream.replace get_list_parameter(@target_list)["turbo_name"], partial: "list", locals: { list_object: get_list_parameter(@target_list)} %>

app/views/random_sets/edit.html.erb
<%= turbo_frame_tag "random_set" do %>
  <div class="mx-4 p-4 mt-5">
    <%= render "random_set_info" %>

    <div class="card mt-3">
      <div class="card-header">
        <div class="row">
          <div class="col-6 mt-auto">
            <i class="bi bi-database">セット内容</i>
          </div>
          <div class="col d-flex justify-content-end mt-auto">
            <%= link_to "", new_random_set_lottery_path(random_set_id: @random_set.id),
              class: "btn btn-primary btn-small bi bi-plus-circle rounded-5",
              data: { turbo_frame: "modal", controller: "tooltip", tooltip: "追加" }
            %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <ul class="list-unstyled">
          <%= render partial: "lotteries/edit_lotteries_list", locals: { lotteries: @lotteries } %>      
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/random_sets/edit.turbo_stream.erb
<%= turbo_stream.append "info_form", partial: "flash" %>
<%= turbo_stream.replace "random_set_info" do %>
  <%= render "random_set_info" %>
<% end %>

app/views/random_sets/edit_list.html.erb
<%= render "modal", title: "レアリティ情報の変更" do %>
  <%= render "list_form", action: "edit", submit_button: "更新", target: params[:list_reality], reality_value: params[:reality_value] %>
<% end %>

app/views/random_sets/new_list.html.erb
<%= render "modal", title: "新規" do %>
  <%= render "list_form", action: "new", submit_button: "作成", reality_value: get_list_parameter(params[:target_list])["min_value"] ? -1 : 0 %>
<% end %>

app/views/random_sets/update.turbo_stream.erb
<%= turbo_stream.append "flashes", partial: "flash" %>
<%= turbo_stream.update "random_set_info", partial: "random_set_info" %>