config/routes.rb
Rails.application.routes.draw do
  resources :random_sets  do
    resources :lotteries, only: [ :new, :create, :index, :edit, :update, :destroy ]
  end
  resources :users, only: %i[new create show edit update destroy]
  get "/favorite/:id/:random_set_id", to: "favorite#flip_favorite", as: "flip_favorite"
  delete "/users/:id/:random_set_id", to: "users#destroy_list", as: "user_destroy_list"
  get "/random_sets/:id/new_list", to: "random_sets#new_list", as: "new_list"
  post "/random_sets/:id/create_list", to: "random_sets#create_list", as: "create_list"
  get "/random_sets/:id/edit_list", to: "random_sets#edit_list", as: "edit_list"
  post "/random_sets/:id/update_list", to: "random_sets#update_list", as: "update_list"
  delete "/random_sets/:id/destroy_list", to: "random_sets#destroy_list", as: "destroy_list"
  get "/login/:id", to: "session#new", as: "login"
  post "/login/:id", to: "session#create", as: "create_login"
  delete "/logout/:id", to: "session#destroy", as: "logout"
  get "/home", to: "static_pages#home"
  get "/guide", to: "static_pages#guide"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include ApplicationHelper
  include SessionHelper
  def check_loggin?
    if current_set_session.nil?
      redirect_to root_path
    else
      true
    end
  end
  def check_user_loggin?
    current_user_session.nil? ? redirect_to(root_path) : true
  end
  def default_url_options
    { locale: I18n.locale }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<%# 通常時 %>
<% if flash.notice %>
  <div class="mb-2 toast hide border-primary" data-controller="toast" data-toast-target="infoToast">
    <div class="toast-header text-primary bg-through">
      <strong class="me-auto">
        <span class="bi bi-check-circle">
          成功
        </span>
      </strong>
    </div>
    <div class="toast-body">
      <%= notice %>
    </div>
  </div>
<% end %>

<%# 失敗時 %>
<% if flash.alert %>
  <div class="mb-2 toast hide border-danger" data-controller="toast" data-toast-target="infoToast">
    <div class="toast-header text-danger bg-through">
      <strong class="me-auto">
        <span class="bi bi-exclamation-circle">
          失敗
        </span>
      </strong>
    </div>
    <div class="toast-body">
      <%= alert %>
    </div>
  </div>
<% end %>

app/views/application/_form_flash.html.erb
<% if object.errors.any? %>
  <div id="errorMessage">
    <div class="alert alert-danger">
      <%= pluralize(object.errors.count, "個の問題")  %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/application/_header.html.erb
<header class="navbar navber-fixed-top bg-dark">
  <nav class="navbar navbar-expand px-4 py-0 d-flex flex-grow-1">
    <div class="pe-3 vertical-line">
      <%= link_to "Randomizer App", root_path, class: "text-white display-7 text-decoration-none" %>
    </div>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-center align-items-center">
      <li class="nav-item">
        <%= link_to "セット作成", new_random_set_path, class: "nav-link link-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "セット検索", random_sets_path, class: "nav-link link-light" %>
      </li>
      <li class="nav-item">
        <%= link_to "利用方法", guide_path, class: "nav-link link-light" %>
      </li>
    </ul>
    <ul class="navbar-nav d-flex text-center text-white">
      <li class="nav-item">
        <% if user_logged_in? %>
            <%= link_to @current_user.user_id, user_path(@current_user), class: "bi bi-person nav-link link-light" %>
        <% else %>
          <%= link_to "ログイン", login_path(id: 0, session_mode: "user", title: "ユーザーログイン"),
            class: "nav-link link-light",
            data: { turbo_frame: "modal" }
          %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/application/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/application/_preview_modal.html.erb
<%= turbo_frame_tag "preview_modal" do %>
  <div class="modal fade" data-controller="preview_modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">カードセット：<%= title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/application/_randomset_lotteries.html.erb
<%# 最上位行 %>
<%= turbo_frame_tag "random_set_lotteries" do %>
  <% if @lotteries.empty? %>
    <p>登録がありません</p>
  <% else %>
    <table id="lotteriesTable" class="table table-hover table-striped table-sm" data-controller="table-sort">
      <thead>
        <tr>
          <th class="sortable col-1" data-sort="checkbox" data-action="click->table-sort#checkboxSort" data-table-sort-target="tableHeader" data-controller="tooltip" data-tooltip="チェックが入っているものだけを引くこともできます。">
            <input class="form-check-input" type="checkbox" data-table-sort-target="checkboxHeader" checked>
          </th>
          <th class="sortable col-1" data-sort="pickup" data-action="click->table-sort#sort" data-table-sort-target="tableHeader" data-controller="tooltip" data-tooltip="ピックアップの設定です。ダブルクリックで切り替えることが行えます。">
            <span class="bi bi-stars"></span>
          </th>
          <% if defined?(@random_set) != nil && params[:action] == "show" %>
            <th class="sortable col-1" data-sort="pickup" data-action="click->table-sort#sort" data-table-sort-target="tableHeader" data-controller="tooltip" data-tooltip="指定引の設定です。ダブルクリックで切り替えることができます。">
              <span class="bi bi-hand-index-fill"></span>
            </th>
          <% end %>
          <th class="sortable col-1" data-sort="number" data-action="click->table-sort#sort" data-table-sort-target="tableHeader"><%= t("common.reality") %></th>
          <th class="sortable col-3" data-sort="string" data-action="click->table-sort#sort" data-table-sort-target="tableHeader"><%= t("common.name") %></th>   
          <% if defined?(@random_set) != nil %>
            <th class="sortable col-1" data-sort="reverse_number" data-action="click->table-sort#sort" data-table-sort-target="tableHeader"><%= t("common.value") %></th>
          <% end %>
          <th class="sortable col-4" data-sort="string" data-action="click->table-sort#sort" data-table-sort-target="tableHeader"><%= t("common.dict") %></th>     
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <%= render @lotteries %>
      </tbody>
    </table>
  <% end %>
<% end %>